<a href="https://colab.research.google.com/github/umair986/ML_basics/blob/main/SVM_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.svm import SVC

In [2]:

df = pd.read_csv('/content/Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.size

10692

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
df_new =df.drop(['Cabin','Name','Embarked','Ticket'], axis = 1)
df_new

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0              1         0       3    male  22.0      1      0   7.2500
1              2         1       1  female  38.0      1      0  71.2833
2              3         1       3  female  26.0      0      0   7.9250
3              4         1       1  female  35.0      1      0  53.1000
4              5         0       3    male  35.0      0      0   8.0500
..           ...       ...     ...     ...   ...    ...    ...      ...
886          887         0       2    male  27.0      0      0  13.0000
887          888         1       1  female  19.0      0      0  30.0000
888          889         0       3  female   NaN      1      2  23.4500
889          890         1       1    male  26.0      0      0  30.0000
890          891         0       3    male  32.0      0      0   7.7500

[891 rows x 8 columns]

In [10]:
total = df.isnull().sum().sort_values(ascending=False)
total

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [11]:
df_new['Age']=df_new['Age'].fillna(0)
df_new['Age']=df_new['Age'].astype(int)
df_new['Age'].replace(0,df_new['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    23.783389
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [12]:
df_new['Age'].isnull().sum()

0

In [13]:
df_new['Pclass'].isnull().sum()

0

In [14]:
df_new['Sex'].replace(['female','male'],[0,1],inplace = True)
df_new

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch     Fare
0              1         0       3    1   22      1      0   7.2500
1              2         1       1    0   38      1      0  71.2833
2              3         1       3    0   26      0      0   7.9250
3              4         1       1    0   35      1      0  53.1000
4              5         0       3    1   35      0      0   8.0500
..           ...       ...     ...  ...  ...    ...    ...      ...
886          887         0       2    1   27      0      0  13.0000
887          888         1       1    0   19      0      0  30.0000
888          889         0       3    0    0      1      2  23.4500
889          890         1       1    1   26      0      0  30.0000
890          891         0       3    1   32      0      0   7.7500

[891 rows x 8 columns]

In [15]:
Y = df_new['Survived']
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [16]:
X = df_new.drop(['Survived'], axis = 'columns')
X

     PassengerId  Pclass  Sex  Age  SibSp  Parch     Fare
0              1       3    1   22      1      0   7.2500
1              2       1    0   38      1      0  71.2833
2              3       3    0   26      0      0   7.9250
3              4       1    0   35      1      0  53.1000
4              5       3    1   35      0      0   8.0500
..           ...     ...  ...  ...    ...    ...      ...
886          887       2    1   27      0      0  13.0000
887          888       1    0   19      0      0  30.0000
888          889       3    0    0      1      2  23.4500
889          890       1    1   26      0      0  30.0000
890          891       3    1   32      0      0   7.7500

[891 rows x 7 columns]

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [21]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2,random_state = True)

In [22]:
model = SVC()
svc = model.fit(X_train,Y_train)

In [23]:
Y_pred = model.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0])

In [24]:
import sklearn.metrics as metrics
metrics.confusion_matrix(Y_test,Y_pred)

array([[104,   2],
       [ 64,   9]])

In [25]:
metrics.classification_report(Y_test,Y_pred)

'              precision    recall  f1-score   support\n\n           0       0.62      0.98      0.76       106\n           1       0.82      0.12      0.21        73\n\n    accuracy                           0.63       179\n   macro avg       0.72      0.55      0.49       179\nweighted avg       0.70      0.63      0.54       179\n'